version: '3.8'
services:
  app:
    build: .
    command: ["/wait-for-it.sh", "neo4j:7687", "--", "node", "dist/main"]
    ports:
      - "3000:3000"
    environment:
      NEO4J_SCHEME: "neo4j"
      NEO4J_HOST: "neo4j"
      NEO4J_PORT: "7687"
      NEO4J_USER: "neo4j"
      NEO4J_PASSWORD: "couchsurfing"
    depends_on:
      neo4j:
        condition: service_healthy
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "neo4j/couchsurfing"
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*"
    volumes:
      - ./data/neo4j:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5
