version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=couchsurfing
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/couchsurfing
    volumes:
      - ./data/neo4j:/data
